# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/mycrocast/mycrocastSwiftRaydioSDK.git'

target 'mycrocastSwiftRaydioSDKExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftRaydioSDK'

  
  
  # Pods for mycrocastSwiftRaydioSDKExample
  
  target 'mycrocastSwiftRaydioSDKExample' do
    inherit! :search_paths
    # Pods for testing
  end

end
