# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/mycrocast/mycrocastRaydioSDKPodsSpec.git'
source 'https://cdn.cocoapods.org/'


target 'mycrocastSwiftRaydioSDKExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftRaydioSDK'


end
